theme: jekyll-theme-cayman
title: [Water in New York]
description: [This is the final project for the Social Data Analysis and Visualization course, taught at DTU in the spring 2022. 
This project assignment investegates water usage, quality and availability in relation to social data.]
